from typing import Protocol, Generator, Set
from src.domain.blocks_world_state import BlocksWorldState


class PlanningContract(Protocol):
    @property
    def current_state(self) -> BlocksWorldState: ...

    @property
    def states(self) -> dict[str, Set[int]]: ...

    @property
    def actions(self) -> dict[str, dict[str, Set[int]]]: ...

    def remap(self, state: Set[int]) -> Set[str]: ...

    def successors(self) -> Generator[BlocksWorldState, None, None]: ...

    def solution(self, goal_state: BlocksWorldState) -> list[str]: ...
    
    def set_goal(self, goal: Set[int]) -> None: ...

    def set_initial(self, initial: Set[int]) -> None: ...
    
    def copy(self) -> PlanningContract: ...
